# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/nebula_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=sql123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# SQL Script Initialization
spring.sql.init.mode=always
spring.sql.init.platform=mysql
spring.sql.init.separator=;;

# Server Settings
server.port=8080

# Razorpay Configuration (Replace with your keys from dashboard)
razorpay.key.id=rzp_test_SbUloyeb67KdLQ
razorpay.key.secret=f8BbwjqOqRBHYN8FcuKKpfPn

